name: Build LaTeX PDF

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          latexmk-flags: "-pdf"
          root_file: content/0_chansonnier.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: built-pdf
          path: content/0_chansonnier.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chansonnier.pdf
          asset_name: chansonnier-${{ github.ref }}.pdf
          asset_content_type: application/pdf